server:
  servlet:
    context-path: /
  port: 8100
logging:
  level:
    org.springframework.web: DEBUG
properties:
  calculate:
    baseUrl: "http://leghe.fantacalcio.it/"
    calendarSuffix: "/calendario"
    rankingSuffix: "/classifica"
  fetcher:
    url: "http://web-fetcher:5000"
